### ISSUE TITLE
Add pagination

### ISSUE THREAD

**Issue by anareaty** [Canna71/obsidian-sets#1]
This plugin is really great! However is would be very useful if we could have pagination in the view. So we can not only limit it to, for example, the fists ten items, but also be able to click the button and see the next ten, and then the next ten, etc. It would help a lot with the big amounts of data.

**Comment by Canna71** [comment]
Sure,  it was one the next steps :-) Thank you very much for trying it out.

**Comment by Canna71** [comment]
Done in 1.0.10
