### ISSUE TITLE
Add ability to transclude images from outside links

### ISSUE THREAD

**Issue by anareaty** [Canna71/obsidian-sets#5]
It seems that it is only possible to transclude images that are locally stored in Obsidian. I would be nice to be able to use images from internet links. If it is already possible, I didn't figure how to do this.

**Comment by Canna71** [comment]
You're right, it is not currently possible. I will have a look, thank you for reporting it.

**Comment by Canna71** [comment]
OK, so I drafted a version which should allow for it.
In the attribute you should put something like

`[<whatever>](link-to-image.jpg)`

Internal image/content should still work. (I use it to link to internal blocks containing books abstract)
I hope this is what you meant.
