### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by JohnV7** [Canna71/obsidian-sets#6]
Hi, I do have problems installing the plugin:

1. I cannot find it under community plugins (restricted mode is off).
2. Downloading it and enabling it leads to error: "Failed to load plugin"

Any idea how to resolve these issues?

Thanks

**Comment by Canna71** [comment]
1. it is not yet published unfortunately I am waiting for somebody from Obsidian to approve it.
2. I could not reproduce it, can you tell me some more details? Maybe if you could reach into developer tools and tell me what is the error, maybe... Also how did you install it? Using BRAT or manually?

Thank you

**Comment by JohnV7** [comment]
1. ok
2. I downloaded the code from github and put in into the plugins folder. It seems that main.js and perhaps other files are missing

app.js:1 
Plugin failure: sets Error: ENOENT: no such file or directory, open '~\.obsidian\plugins\obsidian-sets\main.js'

**Comment by Canna71** [comment]
I see. I guess you have to download the code from the releases. There you find main.js, style.css and manifest.json

**Comment by JohnV7** [comment]
Installing with BRAT worked. Thanks, very useful plugin!

**Comment by Canna71** [comment]
Thank you for trying this!
